ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS pickup_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS pickup_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS drop_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS drop_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS loading_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS loading_stopped_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS unloading_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS unloading_stopped_at TIMESTAMPTZ;